//! Bespoke crypto primitives for the tinc wire protocol.
//!
//! **Nothing in this crate is general-purpose cryptography.** Every module
//! reproduces a specific quirk of tinc's C implementation that prevents
//! off-the-shelf RustCrypto AEAD/KDF/DH crates from interoperating. Each
//! module's doc-comment names the C source it must match byte-for-byte.
//!
//! Correctness is established by Known Answer Tests (`tests/kat.rs`) whose
//! vectors were generated by linking the C code itself (`kat/gen_kat.c`).
//! If a test in this crate fails after a dependency bump, **the dependency
//! changed something protocol-relevant** — do not "fix" the test.

#![forbid(unsafe_code)]
#![warn(missing_docs)]
#![allow(
    clippy::module_name_repetitions,
    // ChaCha, OpenSSH, X25519 etc. are proper nouns, not code identifiers
    clippy::doc_markdown,
)]

pub mod b64;
pub mod chapoly;
pub mod ecdh;
pub mod invite;
pub mod prf;
pub mod sign;
