//! Bespoke crypto primitives for the tinc wire protocol.
//!
//! **Nothing in this crate is general-purpose cryptography.** Every module
//! reproduces a specific quirk of tinc's C implementation that prevents
//! off-the-shelf RustCrypto AEAD/KDF/DH crates from interoperating. Each
//! module's doc-comment names the C source it must match byte-for-byte.
//!
//! Correctness is established by Known Answer Tests (`tests/kat.rs`) whose
//! vectors were generated by linking the C code itself (`kat/gen_kat.c`).
//! If a test in this crate fails after a dependency bump, **the dependency
//! changed something protocol-relevant** — do not "fix" the test.

#![forbid(unsafe_code)]
#![warn(missing_docs, clippy::pedantic)]
#![allow(
    clippy::module_name_repetitions,
    // doc_markdown wants backticks around words like ChaCha, OpenSSH, X25519.
    // These are proper nouns in prose, not code identifiers; backticking them
    // makes the docs read like a ransom note. We keep backticks for actual
    // code (function names, types, file paths) and trust the reader to know
    // what ChaCha is.
    clippy::doc_markdown,
    // We deliberately use .unwrap()/.expect() at points where the failure is
    // structurally impossible (slice-of-known-length → array, HMAC key length)
    // and document why at each site. Forcing # Panics sections for those would
    // make the doc-comments lie about reachability.
    clippy::missing_panics_doc,
)]

pub mod b64;
pub mod chapoly;
pub mod ecdh;
pub mod invite;
pub mod prf;
pub mod sign;
