//! Known Answer Tests against vectors generated by the C implementation.
//!
//! `vectors.json` is produced by `kat/gen_kat.c`, which links the actual
//! `src/chacha-poly1305/`, `src/ed25519/`, `src/nolegacy/` sources. To
//! regenerate after a C-side change: `make -f kat/Makefile`.
//!
//! These tests are the *only* correctness ground truth for `tinc-crypto`.
//! Unit tests inside the crate prove internal consistency; these prove
//! interoperability. A failure here after a dependency bump means the
//! dependency changed something protocol-relevant — investigate the dep,
//! not the test.

use serde::Deserialize;
use tinc_crypto::{b64, chapoly, ecdh, invite, prf, sign};

const VECTORS_JSON: &str = include_str!("kat/vectors.json");

// ─── JSON schema ────────────────────────────────────────────────────────────
// All binary fields are lowercase hex strings. seqno is a decimal string
// because JSON numbers can't represent the full u64 range.

#[derive(Deserialize)]
struct Vectors {
    chapoly: Vec<ChaPolyVec>,
    ecdh: Vec<EcdhVec>,
    prf: Vec<PrfVec>,
    sign: Vec<SignVec>,
    b64: Vec<B64Vec>,
    invitation: Vec<InvitationVec>,
}

#[derive(Deserialize)]
struct ChaPolyVec {
    key: String,
    seqno: String,
    plaintext: String,
    ciphertext: String,
}

#[derive(Deserialize)]
struct EcdhVec {
    seed_a: String,
    priv_a: String,
    pub_a: String,
    seed_b: String,
    // priv_b is in the JSON for completeness/debugging but the test only
    // exercises the from_expanded path on side A. Tell serde to skip it so
    // dead_code doesn't fire.
    #[allow(dead_code)]
    #[serde(skip)]
    priv_b: (),
    pub_b: String,
    shared: String,
}

#[derive(Deserialize)]
struct PrfVec {
    secret: String,
    seed: String,
    out: String,
}

#[derive(Deserialize)]
struct SignVec {
    seed: String,
    expanded_private: String,
    public: String,
    message: String,
    signature: String,
}

#[derive(Deserialize)]
struct B64Vec {
    raw: String,
    encoded_std: String,
    encoded_urlsafe: String,
}

#[derive(Deserialize)]
struct InvitationVec {
    /// Seed for `ed25519_create_keypair`. Regenerating the key from this
    /// (rather than using the JSON's `pubkey` directly) chains the test:
    /// if `sign::SigningKey::from_seed` were broken, this fails too. We
    /// already KAT that separately, but layered tests = layered debugging.
    key_seed: String,
    /// Raw 18-byte cookie.
    cookie: String,
    /// Derived pubkey — we re-derive and compare as a sanity check.
    pubkey: String,
    /// `b64_std(pubkey)`. The string that gets hashed.
    fingerprint: String,
    /// First 24 chars of the URL slug.
    key_hash_b64: String,
    /// Second 24 chars of the URL slug.
    cookie_b64: String,
    /// The invitation filename.
    cookie_hash_b64: String,
}

// ─── helpers ────────────────────────────────────────────────────────────────

fn vectors() -> Vectors {
    serde_json::from_str(VECTORS_JSON).expect("vectors.json is well-formed")
}

/// Decode hex into a fixed-size array, with a useful failure message.
fn hex_arr<const N: usize>(s: &str, what: &str) -> [u8; N] {
    let v = hex::decode(s).unwrap_or_else(|e| panic!("{what}: bad hex: {e}"));
    v.try_into()
        .unwrap_or_else(|v: Vec<u8>| panic!("{what}: want {N} bytes, got {}", v.len()))
}

// ─── tests ──────────────────────────────────────────────────────────────────

#[test]
fn chapoly_seal_matches_c() {
    for (i, v) in vectors().chapoly.iter().enumerate() {
        let key: [u8; 64] = hex_arr(&v.key, "key");
        let seqno: u64 = v.seqno.parse().unwrap();
        let pt = hex::decode(&v.plaintext).unwrap();
        let want = hex::decode(&v.ciphertext).unwrap();

        let cp = chapoly::ChaPoly::new(&key);
        let got = cp.seal(seqno, &pt);

        // Compare hex-encoded so the test output is actually readable when
        // a single byte is off — usually it's an endianness slip in the
        // first or last bytes.
        assert_eq!(
            hex::encode(&got),
            hex::encode(&want),
            "chapoly[{i}] seqno={seqno} ptlen={}",
            pt.len()
        );

        // Round-trip: open(seal(x)) == x. Catches cases where seal and open
        // both have the *same* bug (e.g., wrong nonce endianness on both
        // sides) — the KAT above wouldn't.
        let reopened = cp.open(seqno, &got).expect("round-trip open");
        assert_eq!(reopened, pt, "chapoly[{i}] round-trip");
    }
}

#[test]
fn chapoly_open_rejects_tampered() {
    // Not a KAT, but cheap and worth having: flip one bit, expect rejection.
    // Uses the first KAT vector with a non-empty plaintext as a known-good
    // sealed blob to start from.
    let v = vectors()
        .chapoly
        .into_iter()
        .find(|v| !v.plaintext.is_empty())
        .expect("at least one non-empty chapoly vector");
    let key: [u8; 64] = hex_arr(&v.key, "key");
    let seqno: u64 = v.seqno.parse().unwrap();
    let mut sealed = hex::decode(&v.ciphertext).unwrap();

    let cp = chapoly::ChaPoly::new(&key);
    sealed[0] ^= 1;
    assert!(cp.open(seqno, &sealed).is_err(), "flipped CT byte accepted");
    sealed[0] ^= 1;

    let last = sealed.len() - 1;
    sealed[last] ^= 1;
    assert!(
        cp.open(seqno, &sealed).is_err(),
        "flipped tag byte accepted"
    );
}

#[test]
fn ecdh_from_seed_matches_c() {
    for (i, v) in vectors().ecdh.iter().enumerate() {
        let seed_a: [u8; 32] = hex_arr(&v.seed_a, "seed_a");
        let seed_b: [u8; 32] = hex_arr(&v.seed_b, "seed_b");
        let want_pub_a: [u8; 32] = hex_arr(&v.pub_a, "pub_a");
        let want_pub_b: [u8; 32] = hex_arr(&v.pub_b, "pub_b");
        let want_priv_a: [u8; 64] = hex_arr(&v.priv_a, "priv_a");
        let want_shared: [u8; 32] = hex_arr(&v.shared, "shared");

        // Seed → keypair must reproduce both the public key (Ed25519 point
        // encoding) and the expanded private (SHA-512 + clamp).
        let (priv_a, pub_a) = ecdh::EcdhPrivate::from_seed(&seed_a);
        let (priv_b, pub_b) = ecdh::EcdhPrivate::from_seed(&seed_b);
        assert_eq!(pub_a, want_pub_a, "ecdh[{i}] pub_a");
        assert_eq!(pub_b, want_pub_b, "ecdh[{i}] pub_b");

        // Shared secret, both directions. The C generator already asserted
        // commutativity, but checking again here catches the case where our
        // Edwards→Montgomery map is internally consistent but wrong.
        let shared_ab = priv_a.compute_shared(&pub_b);
        let shared_ba = priv_b.compute_shared(&pub_a);
        assert_eq!(
            hex::encode(shared_ab),
            hex::encode(want_shared),
            "ecdh[{i}] shared a→b"
        );
        assert_eq!(shared_ab, shared_ba, "ecdh[{i}] commutativity");

        // Also exercise the from_expanded path — that's how on-disk keys load.
        let priv_a2 = ecdh::EcdhPrivate::from_expanded(&want_priv_a);
        let shared_a2 = priv_a2.compute_shared(&want_pub_b);
        assert_eq!(shared_a2, want_shared, "ecdh[{i}] from_expanded");
    }
}

#[test]
fn prf_matches_c() {
    for (i, v) in vectors().prf.iter().enumerate() {
        let secret = hex::decode(&v.secret).unwrap();
        let seed = hex::decode(&v.seed).unwrap();
        let want = hex::decode(&v.out).unwrap();

        let mut got = vec![0u8; want.len()];
        prf::prf(&secret, &seed, &mut got);

        assert_eq!(
            hex::encode(&got),
            hex::encode(&want),
            "prf[{i}] secretlen={} seedlen={} outlen={}",
            secret.len(),
            seed.len(),
            want.len()
        );
    }
}

#[test]
fn sign_matches_c() {
    for (i, v) in vectors().sign.iter().enumerate() {
        let seed: [u8; 32] = hex_arr(&v.seed, "seed");
        let want_expanded: [u8; 64] = hex_arr(&v.expanded_private, "expanded");
        let want_public: [u8; 32] = hex_arr(&v.public, "public");
        let msg = hex::decode(&v.message).unwrap();
        let want_sig: [u8; 64] = hex_arr(&v.signature, "signature");

        let sk = sign::SigningKey::from_seed(&seed);
        assert_eq!(sk.expanded_private(), &want_expanded, "sign[{i}] expanded");
        assert_eq!(sk.public(), &want_public, "sign[{i}] public");

        let got_sig = sk.sign(&msg);
        assert_eq!(
            hex::encode(got_sig),
            hex::encode(want_sig),
            "sign[{i}] msglen={}",
            msg.len()
        );

        // And verify accepts it. Ed25519 is deterministic so this is implied
        // by the above, but it exercises the verify path on real signatures.
        sign::verify(&want_public, &msg, &got_sig).expect("sign[{i}] verify");
    }
}

#[test]
fn b64_encode_matches_c() {
    for (i, v) in vectors().b64.iter().enumerate() {
        let raw = hex::decode(&v.raw).unwrap();

        assert_eq!(b64::encode(&raw), v.encoded_std, "b64[{i}] std encode");
        assert_eq!(
            b64::encode_urlsafe(&raw),
            v.encoded_urlsafe,
            "b64[{i}] urlsafe encode"
        );

        // Decode must accept both alphabets and round-trip to the same bytes.
        assert_eq!(
            b64::decode(&v.encoded_std).as_deref(),
            Some(&raw[..]),
            "b64[{i}] std decode"
        );
        assert_eq!(
            b64::decode(&v.encoded_urlsafe).as_deref(),
            Some(&raw[..]),
            "b64[{i}] urlsafe decode"
        );
    }
}

#[test]
fn b64_decode_accepts_mixed_alphabet() {
    // The party trick: '+' and '-' in the *same* string. The C decoder's
    // union table allows this. No KAT for it because the C *encoder* never
    // produces mixed output, but we must accept what the decoder accepts.
    //
    // Build a mixed string by taking a known urlsafe encoding and swapping
    // alternate special chars to their standard equivalents.
    let v = vectors()
        .b64
        .into_iter()
        .find(|v| v.encoded_urlsafe.contains('-') || v.encoded_urlsafe.contains('_'))
        .expect("at least one vector with special chars");
    let raw = hex::decode(&v.raw).unwrap();

    let mut mixed = String::new();
    let mut flip = false;
    for c in v.encoded_urlsafe.chars() {
        mixed.push(match c {
            '-' if flip => '+',
            '_' if flip => '/',
            other => other,
        });
        if matches!(c, '-' | '_') {
            flip = !flip;
        }
    }
    // Sanity: we actually mixed something.
    assert_ne!(mixed, v.encoded_std);
    assert_ne!(mixed, v.encoded_urlsafe);

    assert_eq!(
        b64::decode(&mixed).as_deref(),
        Some(&raw[..]),
        "mixed-alphabet decode"
    );
}

/// Invitation crypto kernel: the chain of compositions that builds a URL
/// slug. Every stage is a place to be silently wrong; we check them all.
///
/// The C side is `invitation.c:499-518` (cmd_invite) +
/// `protocol_auth.c:199-207` (daemon's filename recovery).
///
/// Why per-stage assertions instead of just checking the final slug:
/// when this fails (and it will, if anyone touches b64 or sha2), "slug
/// is wrong" tells you nothing. "fingerprint matches but key_hash
/// doesn't" tells you the hash boundary is the bug.
#[test]
fn invitation_crypto_kernel_matches_c() {
    for (i, v) in vectors().invitation.iter().enumerate() {
        let seed: [u8; 32] = hex_arr(&v.key_seed, "key_seed");
        let cookie: [u8; invite::COOKIE_LEN] = hex_arr(&v.cookie, "cookie");
        let want_pubkey: [u8; 32] = hex_arr(&v.pubkey, "pubkey");

        // Stage 0: regenerate the key. Chains to the `sign` KAT.
        let sk = sign::SigningKey::from_seed(&seed);
        let pubkey = *sk.public_key();
        assert_eq!(
            pubkey, want_pubkey,
            "case {i}: pubkey mismatch (sign::from_seed disagrees with C)"
        );

        // Stage 1: fingerprint. The b64-STRING-that-gets-hashed.
        // Uses the +/ alphabet, NOT urlsafe — if invite::fingerprint
        // accidentally calls encode_urlsafe, this fires before any hash.
        let fp = invite::fingerprint(&pubkey);
        assert_eq!(fp, v.fingerprint, "case {i}: fingerprint (b64 alphabet?)");
        assert_eq!(fp.len(), 43, "case {i}: fingerprint length");

        // Stage 2: key_hash. sha512(fingerprint)[..18], then b64_url.
        // The hash is over the b64 STRING. If someone "optimizes" to
        // hash the raw pubkey, this fires here and not at slug-compare.
        let kh = invite::key_hash(&pubkey);
        assert_eq!(
            b64::encode_urlsafe(&kh),
            v.key_hash_b64,
            "case {i}: key_hash (hashed raw pubkey instead of b64 string?)"
        );

        // Stage 3: cookie b64 — just an encode, but proves the urlsafe
        // alphabet is used for the URL output.
        assert_eq!(
            b64::encode_urlsafe(&cookie),
            v.cookie_b64,
            "case {i}: cookie b64 (alphabet?)"
        );

        // Stage 4: cookie_hash — the filename. Cookie || fingerprint,
        // cookie FIRST. If the order is swapped, this fires.
        assert_eq!(
            invite::cookie_filename(&cookie, &pubkey),
            v.cookie_hash_b64,
            "case {i}: cookie_hash (cookie/fingerprint order?)"
        );
        assert_eq!(v.cookie_hash_b64.len(), invite::SLUG_PART_LEN);

        // Stage 5: full slug build. By this point each piece has passed,
        // so this proves build_slug puts them in the right order.
        let slug = invite::build_slug(&pubkey, &cookie);
        assert_eq!(slug.len(), invite::SLUG_LEN);
        assert_eq!(
            slug,
            format!("{}{}", v.key_hash_b64, v.cookie_b64),
            "case {i}: full slug"
        );

        // Stage 6: parse_slug recovers the original cookie + key_hash.
        // This is cmd_join's path: it gets the slug from the URL, parses
        // out the cookie to send to the daemon, and the key_hash to
        // verify the daemon's greeting against.
        let (parsed_hash, parsed_cookie) = invite::parse_slug(&slug).unwrap();
        assert_eq!(parsed_cookie, cookie, "case {i}: parsed cookie");
        assert_eq!(parsed_hash, kh, "case {i}: parsed key_hash");
    }
}
