//! `tinc invite NODENAME` — generate an invitation URL for a new node.
//!
//! ## What an invitation is
//!
//! A self-contained capability token that lets a new node join the mesh
//! without manual key shipping. The flow:
//!
//! 1. `tinc invite alice` on an existing node prints a URL:
//!    `myhost:655/KEYHASHCOOKIE...48chars...`
//! 2. You give the URL to alice (out-of-band; the URL is the secret).
//! 3. `tinc join URL` on alice's machine TCP-connects to `myhost:655`,
//!    speaks two lines of meta-protocol, then SPTPS — the inviting daemon
//!    proves it holds the invitation key (`key_hash` check), receives the
//!    cookie, finds the matching invitation file, ships its contents.
//! 4. alice writes a fresh tinc.conf + hosts/ from those contents.
//!
//! Three pieces of crypto state make this work:
//!
//! - **Invitation key** (`invitations/ed25519_key.priv`): one per mesh,
//!   shared by all outstanding invitations. Generated by the *first*
//!   `invite`; re-generated when all invitations expire (so a leaked
//!   key from a year-old invite is useless). The daemon loads this on
//!   startup and uses it as its SPTPS identity for invitation handshakes.
//! - **Cookie** (18 random bytes): one per invitation. Bearer token.
//!   Goes in the URL (b64-encoded) but not on disk.
//! - **Invitation file** (`invitations/HASH`): the per-invitation config
//!   blob. Named by `sha512(cookie || fingerprint)[..18]` so `ls` doesn't
//!   leak the cookie. The daemon recomputes the hash from the cookie
//!   it receives.
//!
//! ## Limitations
//!
//! - Name uniqueness is only checked against `hosts/NAME` on disk, not
//!   against a running daemon.
//! - No automatic daemon reload; the "please restart" warning is always
//!   printed. **TODO**: wire best-effort reload.
//! - The URL host comes from the `Address` config variable; there is no
//!   HTTP probe or tty prompt to discover it.
//! - No `invitation-created` script hook. **TODO**: add once a shared
//!   script runner exists.
//!
//! ## What we tighten
//!
//! - Cookie zeroized on every exit path. We wrap in `Zeroizing` so
//!   Drop handles it.

use std::fs;
use std::io::Write;
use std::path::Path;
use std::time::{Duration, SystemTime};

use rand_core::Rng;
use tinc_conf::Config;
use tinc_crypto::invite::{COOKIE_LEN, SLUG_PART_LEN, build_slug, cookie_filename};
use tinc_crypto::os_rng;
use tinc_crypto::sign::SigningKey;
use zeroize::Zeroizing;

use crate::keypair;
use crate::names::{Paths, check_id};

use super::OpenKind;
use super::exchange::get_my_name;
use super::open_nofollow;
use super::write_private_key;
use super::{CmdError, io_err, makedir};
use std::fmt;

/// Invitation expiry: one week (604800s).
///
/// The `InvitationExpire` config var is daemon-side — it controls how
/// long the *daemon* honors an invitation, not how long `cmd_invite`'s
/// sweep keeps the file. Same default but checked independently.
pub(crate) const EXPIRY: Duration = Duration::from_hours(168);

/// `#` + 63 dashes + `#` = 65 chars. Shared with `cmd::exchange` —
/// the invitation file format reuses the export/import separator
/// because `finalize_join` is essentially a special-cased `import`.
///
/// **Don't reformat.** The count is exact; one off and import treats
/// it as content. The `const _` assert below guards against that.
pub(crate) const SEPARATOR: &str =
    "#---------------------------------------------------------------#";
const _: () = assert!(SEPARATOR.len() == 65);

/// `cmd_invite` returns the URL (so the binary can `println!` it) and a
/// flag for "key was freshly generated, daemon needs reload."
///
/// Why not just print directly: `cmd_join` (when it lands) wants to be
/// testable in-process — `invite()` returns the URL, `join()` consumes
/// it, no subprocess. The binary wrapper does `println!("{url}")`.
#[derive(Debug)]
pub struct InviteResult {
    /// The full invitation URL: `address[:port]/SLUG`. The slug embeds
    /// the cookie; treat as secret.
    pub url: Zeroizing<String>,
    /// True if the invitation key was freshly generated. Binary should
    /// emit "please restart daemon" — daemon won't load the new key
    /// until it does.
    pub key_is_new: bool,
}

/// `tinc invite NODENAME`. `now` is injectable for tests; `netname` feeds the
/// invitation's `NetName =` line (`Paths` only has the resolved confbase). One
/// sequence of validate, mkdir, sweep, key, hash, file, url sharing local
/// state.
///
/// # Errors
/// `BadInput` (invalid or taken name, no `Address` configured) or `Io`.
pub fn invite(
    paths: &Paths,
    netname: Option<&str>,
    invitee: &str,
    now: SystemTime,
) -> Result<InviteResult, CmdError> {
    if !check_id(invitee) {
        return Err(CmdError::BadInput(format!(
            "Invalid name for node: {invitee}"
        )));
    }

    // Needed for the `ConnectTo` line and the host config dump.
    let myname = get_my_name(paths)?;

    // `hosts/alice` exists → alice is already known. Can't invite.
    let host_file = paths.host_file(invitee);
    if host_file.exists() {
        return Err(CmdError::BadInput(format!(
            "A host config file for {invitee} already exists!"
        )));
    }

    // Get our address (for the URL host part) early, so a no-Address
    // failure happens before any files are created.
    let address = get_my_address(paths, &myname)?;

    // makedirs(DIR_INVITATIONS)
    // Mode 0700 — only readable by the daemon's user.
    let inv_dir = paths.invitations_dir();
    makedir(&inv_dir, 0o700)?;

    // Sweep invitations/: unlink 24-char-named files older than a week, count the
    // survivors. Zero survivors means the invitation key can be rotated, rendering
    // any leaked old key useless.
    let live_count = sweep_expired(&inv_dir, now)?;

    // Load or generate invitation key
    let key_path = paths.invitation_key();

    // No live invitations → drop the old key. The next block then
    // sees ENOENT and generates a fresh one. "Rotate on empty."
    if live_count == 0 {
        // Best-effort. ENOENT (no key yet) is fine; other errors
        // (EACCES?) would surface in the open below anyway.
        let _ = fs::remove_file(&key_path);
    }

    // Load existing key, else generate. Corrupt/unreadable key with
    // live invitations → hard error: rotating would invalidate every
    // outstanding URL (each embeds key_hash). live_count==0 already
    // unlinked the file above, so that path hits Err → generate.
    let (sk, key_is_new) = match keypair::read_private(&key_path) {
        Ok(sk) => (sk, false),
        Err(e) if live_count > 0 => {
            return Err(CmdError::BadInput(format!(
                "Could not read invitation key: {e}\n  \
                 {live_count} live invitation(s) depend on this key. \
                 Restore {} or remove the invitations/ directory to start over.",
                key_path.display()
            )));
        }
        Err(_) => {
            let sk = keypair::generate();
            write_invitation_key(&key_path, &sk)?;
            // We set the flag; the binary wrapper attempts the reload.
            (sk, true)
        }
    };

    // The crypto kernel (KAT-tested in tinc-crypto)

    // Cookie: 18 fresh random bytes. Zeroizing — the cookie is the secret.
    let mut cookie = Zeroizing::new([0u8; COOKIE_LEN]);
    os_rng().fill_bytes(&mut *cookie);

    // The pubkey is what fingerprint/key_hash/cookie_hash all derive
    // from. SigningKey carries it.
    let pubkey = sk.public_key();

    // Filename = b64_url(sha512(cookie || b64(pubkey))[..18]).
    // 24 chars, doesn't reveal the cookie.
    let inv_filename = cookie_filename(&cookie, pubkey);
    let inv_path = inv_dir.join(&inv_filename);

    // Write the invitation file, O_EXCL 0600 (an 18-byte random cookie can't
    // collide, so EEXIST is a real problem). Built as one string and written once:
    // testable builder, no partial writes.
    let body = build_invitation_file(paths, netname, invitee, &myname, &address)?;
    write_invitation_file(&inv_path, &body)?;

    // Build the URL
    // The address already has [:port] formatting from get_my_address.
    let slug = Zeroizing::new(build_slug(pubkey, &cookie));
    let url = Zeroizing::new(format!("{address}/{}", *slug));

    // TODO(chunk-8): execute_script("invitation-created") — lifts to
    // shared script.rs with daemon's execute_script.

    Ok(InviteResult { url, key_is_new })
}

/// Expiry sweep plus live count over `inv_dir`: entries with a 24-char
/// (`SLUG_PART_LEN`) name are unlinked if `mtime + 1 week < now`, else counted;
/// other names are skipped. `now` is injectable so tests needn't touch mtimes.
fn sweep_expired(inv_dir: &Path, now: SystemTime) -> Result<u32, CmdError> {
    let deadline = now.checked_sub(EXPIRY).unwrap_or(SystemTime::UNIX_EPOCH);

    let mut count = 0u32;
    let entries = fs::read_dir(inv_dir).map_err(io_err(inv_dir))?;
    for entry in entries {
        // We propagate per-entry errors immediately — if readdir
        // fails partway, the count is meaningless anyway.
        let entry = entry.map_err(io_err(inv_dir))?;
        let name = entry.file_name();

        // The 24-char filter. `OsStr::len()` is bytes; on Unix that's
        // fine. The b64 alphabet is all ASCII, so 24 bytes = 24 chars.
        if name.len() != SLUG_PART_LEN {
            continue;
        }

        let path = entry.path();
        // stat failure is logged-and-skipped, not fatal — `metadata`
        // failing on a single file shouldn't kill the whole sweep.
        let Ok(meta) = entry.metadata() else {
            continue;
        };
        let Ok(mtime) = meta.modified() else {
            // Platform without mtime support? Treat as live; safer
            // than deleting.
            count += 1;
            continue;
        };

        if mtime < deadline {
            // Best-effort; if it fails the next sweep retries.
            let _ = fs::remove_file(&path);
        } else {
            count += 1;
        }
    }
    Ok(count)
}

/// Write the invitation private key.
///
/// `OpenOptions::mode(0600)` sets the mode atomically at create time,
/// so there is no window where the key is world-readable.
///
/// Not `O_EXCL` — we just unlinked it (or it didn't exist).
fn write_invitation_key(path: &Path, sk: &SigningKey) -> Result<(), CmdError> {
    write_private_key(path, sk, OpenKind::CreateTrunc)
}

/// Write the invitation file at 0600 with `O_EXCL`.
fn write_invitation_file(path: &Path, body: &str) -> Result<(), CmdError> {
    let mut f = open_nofollow(path, OpenKind::CreateExcl, 0o600)?;
    f.write_all(body.as_bytes()).map_err(io_err(path))
}

/// Build the invitation file body: chunk 1 is the invitee's bootstrap config
/// (`Name`, `NetName`, `ConnectTo`, copied `Mode`/`Broadcast`), then `#---#`,
/// then our host file (with `Port` substituted if 0). `finalize_join` filters
/// chunk 1 through `VAR_SAFE` and writes later chunks as host files, so the
/// format is daemon-locked. Pure, for tests.
fn build_invitation_file(
    paths: &Paths,
    netname: Option<&str>,
    invitee: &str,
    myname: &str,
    address: &AddressPort,
) -> Result<String, CmdError> {
    let mut out = String::new();

    // Chunk 1: invitee's bootstrap config
    // `Name = X` is the first line; `finalize_join` reads it to know
    // what node it's becoming. Must be first — `get_value` finds the
    // first match.
    out.push_str("Name = ");
    out.push_str(invitee);
    out.push('\n');

    // Emitted only if netname is set. `check_netname` isn't ported yet; the
    // binary's `-n` parser guards path traversal and `finalize_join` re-validates
    // on the receiving side.
    if let Some(n) = netname {
        out.push_str("NetName = ");
        out.push_str(n);
        out.push('\n');
    }

    // Tells the new node who to connect to.
    out.push_str("ConnectTo = ");
    out.push_str(myname);
    out.push('\n');

    // Scan tinc.conf for Mode/Broadcast and copy them. These are the
    // "mesh shape" vars — switch vs router, broadcast yes/no — that
    // the new node needs to match. Everything else is per-node.
    copy_mesh_vars(paths, &mut out)?;

    out.push_str(SEPARATOR);
    out.push('\n');

    // Chunk 2: our host config
    out.push_str("Name = ");
    out.push_str(myname);
    out.push('\n');

    copy_host_replacing_port(&paths.host_file(myname), &address.port, &mut out)?;

    Ok(out)
}

/// Copy `Mode` and `Broadcast` from tinc.conf into the invitation.
///
/// We use `tinc-conf` to parse and re-emit canonically. Whitespace
/// differences in the source (`Mode=switch` vs `Mode = switch`)
/// become canonical in the invitation. Doesn't matter —
/// `finalize_join` re-parses and emits canonically anyway.
fn copy_mesh_vars(paths: &Paths, out: &mut String) -> Result<(), CmdError> {
    let tc = paths.tinc_conf();
    let cfg =
        Config::read(&tc).map_err(|e| CmdError::BadInput(format!("{}: {e}", tc.display())))?;

    // Just two vars; `lookup` is case-insensitive. Only the first match
    // is copied — the daemon's config reader takes first-wins, so
    // duplicates would be noise (and an fsck warning).
    for var in &["Mode", "Broadcast"] {
        if let Some(entry) = cfg.lookup(var).next() {
            out.push_str(var);
            out.push_str(" = ");
            out.push_str(entry.get_str());
            out.push('\n');
        }
    }
    Ok(())
}

/// Copy `hosts/myname` line by line, replacing any `Port` line with `Port =
/// ACTUAL_PORT` so a `Port = 0` config advertises the port from the `Address`
/// line (or 655) rather than 0. Byte-preserving `split_inclusive` copy, not
/// `parse_file`, because the host file carries PEM blocks and comments.
fn copy_host_replacing_port(
    host_file: &Path,
    port: &str,
    out: &mut String,
) -> Result<(), CmdError> {
    // Match when the first whitespace-delimited token is exactly `Port`,
    // case-insensitive (`Porting` and `Port=655` don't match; init writes `Port =
    // X`). `split_inclusive('\n')` keeps trailing newlines like a `read_line`
    // loop.
    let body = fs::read_to_string(host_file).map_err(io_err(host_file))?;

    for chunk in body.split_inclusive('\n') {
        let trimmed = chunk.strip_suffix('\n').unwrap_or(chunk);

        // Leading whitespace skipped, then first token until \t or space.
        let after_lead = trimmed.trim_start_matches([' ', '\t']);
        let token_end = after_lead.find([' ', '\t']).unwrap_or(after_lead.len());
        let token = &after_lead[..token_end];

        if token.len() == 4 && token.eq_ignore_ascii_case("Port") {
            // Replace. Always emits a newline regardless of whether
            // the input chunk had one.
            out.push_str("Port = ");
            out.push_str(port);
            out.push('\n');
        } else {
            // Pass through verbatim, including whatever newline
            // (or lack thereof) the chunk had.
            out.push_str(chunk);
        }
    }
    Ok(())
}

/// Our `host[:port]` for the URL: `Address` from the host file, then tinc.conf,
/// else a clear error. Without a daemon connection `Port = 0` can't be resolved
/// from the pidfile, so it needs a port on the `Address` line.
fn get_my_address(paths: &Paths, myname: &str) -> Result<AddressPort, CmdError> {
    // We handle `Address = host port` (port-on-address-line) —
    // `Address = 1.2.3.4 1234` ≡ `Address = 1.2.3.4` + `Port = 1234`.
    //
    // We skip the tinc.conf fallback for Address — it's a host var,
    // not a server var; fsck would warn (`HostVarInServer`). If
    // someone has that setup, they'll get "set Address in your host
    // file" which is the right fix.

    let host_file = paths.host_file(myname);
    let cfg = Config::read(&host_file)
        .map_err(|e| CmdError::BadInput(format!("{}: {e}", host_file.display())))?;

    // Address: required. C falls through to HTTP probe + tty prompt;
    // we bail. The error message tells the user what to do.
    let Some(addr_entry) = cfg.lookup("Address").next() else {
        return Err(CmdError::BadInput(format!(
            "No Address found in {}.\n  hint: run `tinc -n NET add Address <public-ip-or-hostname>` before creating invitations.",
            host_file.display()
        )));
    };
    let addr_value = addr_entry.get_str();

    // After `Address = X Y`, X is hostname, Y (if present) is port.
    // tinc-conf gives us the raw value after `=`; split once.
    let mut parts = addr_value.split_whitespace();
    let host = parts
        .next()
        .ok_or_else(|| CmdError::BadInput("Address value is empty".into()))?
        .to_owned();
    let addr_line_port = parts.next().map(str::to_owned);

    // Port: from Address line (highest precedence), then `Port =`
    // config entry, then default 655.
    let port = if let Some(p) = addr_line_port {
        p
    } else if let Some(port_entry) = cfg.lookup("Port").next() {
        let p = port_entry.get_str().to_owned();
        // Port=0 means ephemeral; the daemon writes the real port to
        // the pidfile. No daemon → can't resolve → bail.
        if p == "0" {
            return Err(CmdError::BadInput(
                "Port = 0 means dynamic port allocation, but tincd is not running. \
                 Please start tincd or set Port to a fixed value."
                    .into(),
            ));
        }
        p
    } else {
        // Default port: 655. `cmd_join` uses `"655"` if no port in
        // URL; daemon binds 655 by default. All consistent.
        String::from("655")
    };

    Ok(AddressPort { host, port })
}

/// Host + port pair, with the URL formatting that handles IPv6.
///
/// Separate struct (not a tuple) because the formatting rule is
/// non-obvious and lives with the data: IPv6 literals need `[]`
/// brackets in URLs.
#[derive(Debug)]
struct AddressPort {
    host: String,
    /// Kept as a string, not u16: ports can be service names
    /// (`Port = tinc` → `getaddrinfo("tinc")` → 655). String
    /// round-trips.
    port: String,
}

impl fmt::Display for AddressPort {
    /// The colon check is a "is this IPv6" heuristic; hostnames
    /// can't contain colons, IPv4 can't, only IPv6 literals do.
    /// `[::1]:655` not `::1:655` (ambiguous).
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.host.contains(':') {
            write!(f, "[{}]:{}", self.host, self.port)
        } else {
            write!(f, "{}:{}", self.host, self.port)
        }
    }
}

// Tests

#[cfg(all(test, unix))]
mod tests {
    use super::*;
    use crate::cmd::init;
    use crate::testutil;
    use crate::testutil::ConfDir;
    use std::os::unix::fs::PermissionsExt;

    /// `tinc init NAME` then append `Address = HOST` to `hosts/NAME`.
    /// init doesn't write Address (it's per-installation, not
    /// per-node-identity); invite needs it.
    fn init_with_address(paths: &Paths, name: &str, addr: &str) {
        init::run(paths, name).unwrap();
        let host_file = paths.host_file(name);
        let mut f = fs::OpenOptions::new()
            .append(true)
            .open(&host_file)
            .unwrap();
        writeln!(f, "Address = {addr}").unwrap();
    }

    // copy_host_replacing_port — the C tokenizer port

    /// `copy_host_replacing_port` table. Helper closure does the
    /// tempdir+write+call dance once per row.
    #[test]
    fn copy_host_table() {
        let case = |input: &str, port: &str, expected: &str| {
            let (_dir, f) = testutil::scratch_file("h", input);
            let mut out = String::new();
            copy_host_replacing_port(&f, port, &mut out).unwrap();
            assert_eq!(out, expected, "input: {input:?} port: {port:?}");
        };

        // Port line replaced, everything else byte-preserved.
        case(
            "Address = 1.2.3.4\nPort = 0\nEd25519PublicKey = abc\n",
            "12345",
            "Address = 1.2.3.4\nPort = 12345\nEd25519PublicKey = abc\n",
        );
        // `Port=655` (no space before `=`) does not match. The
        // tokenizer stops at whitespace, not `=`, so the token is
        // `Port=655` (8 chars), not `Port` (4 chars).
        case("Port=0\n", "12345", "Port=0\n");
        // No trailing newline on last line: preserved.
        case("Subnet = 10.0.0.0/24", "655", "Subnet = 10.0.0.0/24");
        // Case-insensitive match. Both replaced.
        case("PORT = 0\nport = 1\n", "x", "Port = x\nPort = x\n");
        // PEM block preserved byte-exact. This is why we DON'T use
        // `parse_file` for the host copy — it would silently drop the
        // PEM block (and comments, and blank lines).
        let pem =
            "-----BEGIN ED25519 PUBLIC KEY-----\nbase64here\n-----END ED25519 PUBLIC KEY-----\n";
        case(
            &format!("Port = 1\n{pem}"),
            "655",
            &format!("Port = 655\n{pem}"),
        );
    }

    // get_my_address

    #[test]
    fn address_basic() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        init_with_address(&paths, "alice", "myhost.example");
        let a = get_my_address(&paths, "alice").unwrap();
        assert_eq!(a.host, "myhost.example");
        assert_eq!(a.port, "655"); // default
        assert_eq!(a.to_string(), "myhost.example:655");
    }

    #[test]
    fn address_with_port_on_line() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        init_with_address(&paths, "alice", "1.2.3.4 9999");
        let a = get_my_address(&paths, "alice").unwrap();
        assert_eq!(a.host, "1.2.3.4");
        assert_eq!(a.port, "9999");
    }

    #[test]
    fn address_ipv6_brackets() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        init_with_address(&paths, "alice", "fe80::1");
        let a = get_my_address(&paths, "alice").unwrap();
        // Colon in host → bracketed in URL.
        assert_eq!(a.to_string(), "[fe80::1]:655");
    }

    #[test]
    fn address_port_from_config() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        init_with_address(&paths, "alice", "myhost");
        let mut f = fs::OpenOptions::new()
            .append(true)
            .open(paths.host_file("alice"))
            .unwrap();
        writeln!(f, "Port = 1234").unwrap();
        let a = get_my_address(&paths, "alice").unwrap();
        assert_eq!(a.port, "1234");
    }

    #[test]
    fn address_port_zero_bails() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        init_with_address(&paths, "alice", "myhost");
        let mut f = fs::OpenOptions::new()
            .append(true)
            .open(paths.host_file("alice"))
            .unwrap();
        writeln!(f, "Port = 0").unwrap();
        let err = get_my_address(&paths, "alice").unwrap_err();
        let CmdError::BadInput(msg) = err else {
            panic!("wrong variant: {err:?}")
        };
        assert!(msg.contains("dynamic port"), "{msg}");
        assert!(msg.contains("tincd"), "{msg}");
    }

    #[test]
    fn address_missing_bails() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        init::run(&paths, "alice").unwrap(); // no Address
        let err = get_my_address(&paths, "alice").unwrap_err();
        let CmdError::BadInput(msg) = err else {
            panic!("wrong variant: {err:?}")
        };
        assert!(msg.contains("No Address"), "{msg}");
    }

    // sweep_expired

    /// 24-char filename → counted. Other lengths → ignored. The
    /// `ed25519_key.priv` (16 chars) and `.` `..` filter.
    #[test]
    fn sweep_filters_by_filename_length() {
        let dir = tempfile::tempdir().unwrap();
        let inv = dir.path().join("inv");
        fs::create_dir(&inv).unwrap();

        // 24 chars: counted.
        fs::write(inv.join("a".repeat(24)), "").unwrap();
        fs::write(inv.join("b".repeat(24)), "").unwrap();
        // 16 chars (the key): not counted.
        fs::write(inv.join("ed25519_key.priv"), "").unwrap();
        // 23 chars: not counted.
        fs::write(inv.join("c".repeat(23)), "").unwrap();

        let count = sweep_expired(&inv, SystemTime::now()).unwrap();
        assert_eq!(count, 2);

        // Nothing deleted (all fresh).
        assert_eq!(fs::read_dir(&inv).unwrap().count(), 4);
    }

    /// Expired files deleted, fresh files survive. `now` parameterized
    /// so we don't need to mess with futimes.
    #[test]
    fn sweep_deletes_expired() {
        let dir = tempfile::tempdir().unwrap();
        let inv = dir.path().join("inv");
        fs::create_dir(&inv).unwrap();

        let live = inv.join("a".repeat(24));
        let dead = inv.join("z".repeat(24));
        fs::write(&live, "").unwrap();
        fs::write(&dead, "").unwrap();

        // Both files were just written with the same mtime, so backdate `dead` via
        // `nix` utimes (already a dep) instead of sleeping.
        let old = SystemTime::UNIX_EPOCH + Duration::from_secs(1_000_000);
        let old_tv = nix::sys::time::TimeVal::new(1_000_000, 0);
        nix::sys::stat::utimes(&dead, &old_tv, &old_tv).unwrap();

        // now = 8 days after `dead`'s mtime. `dead` is expired
        // (deadline = now - 7d = old + 1d > old). `live` has mtime
        // = real-now, well after the deadline.
        let sweep_now = old + Duration::from_hours(192);

        let count = sweep_expired(&inv, sweep_now).unwrap();
        assert_eq!(count, 1, "live should be counted, dead should not");
        assert!(live.exists());
        assert!(!dead.exists(), "dead should be deleted");
    }

    // invite() — the contract test

    /// Full invite on a clean init: creates invitations/, key, file,
    /// returns a 48-char-slug URL. **The contract test.**
    ///
    /// What this proves over the unit tests above: the pieces compose.
    /// `invite()` is the seam — every helper is exercised.
    #[test]
    fn invite_full_flow() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        let confbase = cd.confbase();
        init_with_address(&paths, "alice", "myhost.example");

        let r = invite(&paths, Some("testnet"), "bob", SystemTime::now()).unwrap();

        // Key was freshly generated (first invite).
        assert!(r.key_is_new);

        // URL shape: host:port/slug, slug is 48 chars.
        let url = r.url.as_str();
        let slash = url.rfind('/').unwrap();
        assert_eq!(&url[..slash], "myhost.example:655");
        let slug = &url[slash + 1..];
        assert_eq!(slug.len(), tinc_crypto::invite::SLUG_LEN);

        // Slug parses. (KAT proves the bytes are right; this proves
        // `invite()` actually called `build_slug`.)
        let (hash, cookie) = tinc_crypto::invite::parse_slug(slug).unwrap();

        // invitations/ exists, mode 0700.
        let inv_dir = confbase.join("invitations");
        let mode = fs::metadata(&inv_dir).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o700);

        // Invitation key exists, mode 0600, loads.
        let key_path = inv_dir.join("ed25519_key.priv");
        assert!(key_path.exists());
        let kmode = fs::metadata(&key_path).unwrap().permissions().mode();
        assert_eq!(kmode & 0o777, 0o600);
        let sk = keypair::read_private(&key_path).unwrap();

        // **The contract**: the URL's key_hash matches the key on
        // disk. This is what `cmd_join` will verify after the daemon
        // greeting — if it fails, "Peer has an invalid key".
        assert_eq!(hash, tinc_crypto::invite::key_hash(sk.public_key()));

        // **The other contract**: the invitation file's name is
        // recoverable from (cookie, key). This is what the daemon
        // does in `receive_invitation_sptps`. If it fails,
        // "non-existing invitation".
        let expected_filename = tinc_crypto::invite::cookie_filename(&cookie, sk.public_key());
        let inv_file = inv_dir.join(&expected_filename);
        assert!(
            inv_file.exists(),
            "filename should be recoverable from cookie+key; \
             expected {expected_filename}, dir has: {:?}",
            fs::read_dir(&inv_dir)
                .unwrap()
                .map(|e| e.unwrap().file_name())
                .collect::<Vec<_>>()
        );

        // Invitation file mode 0600.
        let fmode = fs::metadata(&inv_file).unwrap().permissions().mode();
        assert_eq!(fmode & 0o777, 0o600);

        // File contents: chunk 1 has Name=bob first, NetName,
        // ConnectTo=alice. Chunk 2 has Name=alice + alice's host
        // config (with the pubkey).
        let body = fs::read_to_string(&inv_file).unwrap();
        assert!(
            body.starts_with("Name = bob\n"),
            "Name must be first line: {body}"
        );
        assert!(body.contains("NetName = testnet\n"));
        assert!(body.contains("ConnectTo = alice\n"));
        assert!(body.contains(SEPARATOR));
        // Chunk 2 starts with Name = alice.
        let chunk2 = body.split(SEPARATOR).nth(1).unwrap();
        assert!(chunk2.contains("Name = alice\n"));
        // alice's pubkey is in chunk 2 (init wrote it as a config line).
        assert!(chunk2.contains("Ed25519PublicKey = "));
    }

    /// Corrupt key + live invitations → refuse, don't rotate (would
    /// brick every outstanding URL). C parity.
    #[test]
    fn corrupt_key_with_live_invites_not_clobbered() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        init_with_address(&paths, "alice", "myhost");

        // First invite: creates key + invitation file for bob.
        let r1 = invite(&paths, None, "bob", SystemTime::now()).unwrap();
        assert!(r1.key_is_new);

        let key_path = paths.invitation_key();
        fs::write(&key_path, "garbage, not PEM\n").unwrap();

        let err = invite(&paths, None, "carol", SystemTime::now()).unwrap_err();
        let CmdError::BadInput(msg) = err else {
            panic!("wrong variant: {err:?}")
        };
        assert!(msg.contains("invitation key"), "{msg}");
        assert!(msg.contains("live invitation"), "{msg}");

        // Nothing on disk touched.
        assert_eq!(fs::read_to_string(&key_path).unwrap(), "garbage, not PEM\n");
        let invites: Vec<_> = fs::read_dir(paths.invitations_dir())
            .unwrap()
            .map(|e| e.unwrap().file_name())
            .filter(|n| n.len() == SLUG_PART_LEN)
            .collect();
        assert_eq!(invites.len(), 1);
    }

    /// Second invite reuses the key (not freshly generated). The
    /// "rotate on empty" logic only fires when count == 0.
    #[test]
    fn second_invite_reuses_key() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        init_with_address(&paths, "alice", "myhost");

        let r1 = invite(&paths, None, "bob", SystemTime::now()).unwrap();
        assert!(r1.key_is_new);

        let r2 = invite(&paths, None, "carol", SystemTime::now()).unwrap();
        assert!(!r2.key_is_new, "second invite should reuse key");

        // Same key → same key_hash in both URLs.
        let slug1 = r1.url.rsplit('/').next().unwrap();
        let slug2 = r2.url.rsplit('/').next().unwrap();
        assert_eq!(
            slug1[..SLUG_PART_LEN],
            slug2[..SLUG_PART_LEN],
            "key_hash should match (same invitation key)"
        );
        // Different cookies → different cookie halves.
        assert_ne!(slug1[SLUG_PART_LEN..], slug2[SLUG_PART_LEN..]);
    }

    /// invite("alice") when hosts/alice already exists → fail.
    /// You can't invite a node you already know about.
    #[test]
    fn invite_existing_host_fails() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        init_with_address(&paths, "alice", "myhost");
        // hosts/alice exists (init created it). Inviting alice fails.
        let err = invite(&paths, None, "alice", SystemTime::now()).unwrap_err();
        let CmdError::BadInput(msg) = err else {
            panic!("wrong variant: {err:?}")
        };
        assert!(msg.contains("already exists"));
    }

    /// invite with no Address → clear error before any files created.
    /// The "fail early" reorder.
    #[test]
    fn invite_no_address_fails_clean() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        let confbase = cd.confbase();
        init::run(&paths, "alice").unwrap(); // no Address

        let err = invite(&paths, None, "bob", SystemTime::now()).unwrap_err();
        let CmdError::BadInput(msg) = err else {
            panic!("wrong variant: {err:?}")
        };
        assert!(msg.contains("No Address"));

        // Nothing created: a no-Address failure must leave no trace
        // (the address is resolved before any files are written).
        assert!(
            !confbase.join("invitations").exists(),
            "no-Address failure should not create invitations/"
        );
    }

    /// Invalid invitee name → fail before anything else.
    #[test]
    fn invite_bad_name_fails() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        init_with_address(&paths, "alice", "myhost");
        let err = invite(&paths, None, "../etc", SystemTime::now()).unwrap_err();
        assert!(matches!(err, CmdError::BadInput(_)));
    }

    /// `Mode` and `Broadcast` from tinc.conf get copied. Nothing
    /// else does.
    #[test]
    fn mesh_vars_copied() {
        let cd = ConfDir::bare();
        let paths = cd.paths().clone();
        let confbase = cd.confbase();
        init_with_address(&paths, "alice", "myhost");

        let mut tc = fs::OpenOptions::new()
            .append(true)
            .open(confbase.join("tinc.conf"))
            .unwrap();
        // Mode and Broadcast → copied. Device → not copied.
        writeln!(tc, "Mode = switch").unwrap();
        writeln!(tc, "Broadcast = no").unwrap();
        writeln!(tc, "Device = /dev/net/tun").unwrap();
        drop(tc);

        let r = invite(&paths, None, "bob", SystemTime::now()).unwrap();
        let slug = r.url.rsplit('/').next().unwrap();
        let (_, cookie) = tinc_crypto::invite::parse_slug(slug).unwrap();
        let sk = keypair::read_private(&paths.invitation_key()).unwrap();
        let inv_file = paths
            .invitations_dir()
            .join(tinc_crypto::invite::cookie_filename(
                &cookie,
                sk.public_key(),
            ));
        let body = fs::read_to_string(inv_file).unwrap();

        // Chunk 1 (before separator) has Mode + Broadcast.
        let chunk1 = body.split(SEPARATOR).next().unwrap();
        assert!(chunk1.contains("Mode = switch\n"));
        assert!(chunk1.contains("Broadcast = no\n"));
        // Device is not copied. Not in the filter.
        assert!(!chunk1.contains("Device"));
    }
}
