//! `tinc invite NODENAME` — generate an invitation URL for a new node.
//!
//! ## What an invitation is
//!
//! A self-contained capability token that lets a new node join the mesh
//! without manual key shipping. The flow:
//!
//! 1. `tinc invite alice` on an existing node prints a URL:
//!    `myhost:655/KEYHASHCOOKIE...48chars...`
//! 2. You give the URL to alice (out-of-band; the URL is the secret).
//! 3. `tinc join URL` on alice's machine TCP-connects to `myhost:655`,
//!    speaks two lines of meta-protocol, then SPTPS — the inviting daemon
//!    proves it holds the invitation key (`key_hash` check), receives the
//!    cookie, finds the matching invitation file, ships its contents.
//! 4. alice writes a fresh tinc.conf + hosts/ from those contents.
//!
//! Three pieces of crypto state make this work:
//!
//! - **Invitation key** (`invitations/ed25519_key.priv`): one per mesh,
//!   shared by all outstanding invitations. Generated by the *first*
//!   `invite`; re-generated when all invitations expire (so a leaked
//!   key from a year-old invite is useless). The daemon loads this on
//!   startup and uses it as its SPTPS identity for invitation handshakes.
//! - **Cookie** (18 random bytes): one per invitation. Bearer token.
//!   Goes in the URL (b64-encoded) but NOT on disk.
//! - **Invitation file** (`invitations/HASH`): the per-invitation config
//!   blob. Named by `sha512(cookie || fingerprint)[..18]` so `ls` doesn't
//!   leak the cookie. The daemon recomputes the hash from the cookie
//!   it receives.
//!
//! ## What we drop from upstream
//!
//! - Daemon name-uniqueness check: best-effort upstream, degrades to
//!   no-op when daemon's down. The `hosts/NAME` exists check (kept)
//!   covers the disk case.
//! - Daemon reload: we always print the "please restart" warning.
//!   `invite` is `needs_daemon: false`. **TODO(chunk-8)**: wire
//!   best-effort reload.
//! - `get_my_hostname` HTTP probe: hand-crafted `GET /host.cgi` to
//!   `tinc-vpn.org:80` to discover our IP. We require `Address` to be
//!   set instead.
//! - `get_my_hostname` tty prompt: same "no prompts" deviation as
//!   init/genkey/fsck.
//! - `execute_script("invitation-created")`: user hook. **TODO**:
//!   lifts to `tinc-tools::script` with daemon's `execute_script`.
//!
//! ## What we tighten
//!
//! - Cookie zeroized on every exit path. We wrap in `Zeroizing` so
//!   Drop handles it.

use std::fs;
use std::io::Write;
use std::path::Path;
use std::time::{Duration, SystemTime};

use rand_core::{OsRng, RngCore};
use tinc_conf::{Config, parse_file};
use tinc_crypto::invite::{COOKIE_LEN, SLUG_PART_LEN, build_slug, cookie_filename};
use tinc_crypto::sign::SigningKey;
use zeroize::Zeroizing;

use crate::keypair;
use crate::names::{Paths, check_id};

use super::exchange::get_my_name;
use super::{CmdError, io_err, makedir};

/// Invitation expiry: one week (604800s).
///
/// The `InvitationExpire` config var is daemon-side — it controls how
/// long the *daemon* honors an invitation, not how long `cmd_invite`'s
/// sweep keeps the file. Same default but checked independently.
pub(crate) const EXPIRY: Duration = Duration::from_secs(604_800);

/// `#` + 63 dashes + `#` = 65 chars. Same string as
/// `cmd::exchange::SEPARATOR` but the modules are independent —
/// re-declared. The invitation file format reuses the export/import
/// separator because `finalize_join` is essentially a special-cased
/// `import`.
pub(crate) const SEPARATOR: &str =
    "#---------------------------------------------------------------#";
const _: () = assert!(SEPARATOR.len() == 65);

/// `cmd_invite` returns the URL (so the binary can `println!` it) and a
/// flag for "key was freshly generated, daemon needs reload."
///
/// Why not just print directly: `cmd_join` (when it lands) wants to be
/// testable in-process — `invite()` returns the URL, `join()` consumes
/// it, no subprocess. The binary wrapper does `println!("{url}")`.
#[derive(Debug)]
pub struct InviteResult {
    /// The full invitation URL: `address[:port]/SLUG`. The slug embeds
    /// the cookie; treat as secret.
    pub url: Zeroizing<String>,
    /// True if the invitation key was freshly generated. Binary should
    /// emit "please restart daemon" — daemon won't load the new key
    /// until it does.
    pub key_is_new: bool,
}

/// `tinc invite NODENAME`.
///
/// `now` is parameterized for tests; production passes
/// `SystemTime::now()`. Same pattern as `cmd::sign`.
///
/// `netname` threads through to the invitation file's `NetName =` line;
/// `Paths` doesn't carry it (only the *resolved* confbase). `None` =
/// no `NetName` line.
///
/// # Errors
/// - `BadInput`: invalid node name, name collision with existing host,
///   no `Address` in config (we don't probe).
/// - `Io`: any filesystem operation. invitations/ creation, key write,
///   invitation file write.
///
/// # Panics
/// Only via `OsRng::fill_bytes` if the OS entropy source is broken.
/// Same panic contract as `keypair::generate`.
// Sequence of distinct steps (validate, mkdir, sweep, key, hash, file,
// url) sharing local state. Splitting would mean threading 6 args.
pub fn invite(
    paths: &Paths,
    netname: Option<&str>,
    invitee: &str,
    now: SystemTime,
) -> Result<InviteResult, CmdError> {
    if !check_id(invitee) {
        return Err(CmdError::BadInput(format!(
            "Invalid name for node: {invitee}"
        )));
    }

    // Needed for the `ConnectTo` line and the host config dump.
    let myname = get_my_name(paths)?;

    // `hosts/alice` exists → alice is already known. Can't invite.
    let host_file = paths.host_file(invitee);
    if host_file.exists() {
        return Err(CmdError::BadInput(format!(
            "A host config file for {invitee} already exists!"
        )));
    }

    // ─── Get our address (for the URL host part)
    // Done early so failure happens BEFORE we create files. Upstream
    // does it late, which leaves a 0-byte invitation file behind on
    // no-Address failure (it sits in invitations/ until expiry).
    // Ordering it here is cleaner.
    let address = get_my_address(paths, &myname)?;

    // ─── makedirs(DIR_INVITATIONS)
    // Mode 0700 — only readable by the daemon's user.
    let inv_dir = paths.invitations_dir();
    makedir(&inv_dir, 0o700)?;

    // ─── Sweep expired invitations, count live ones
    // Walk invitations/: each file with a 24-char name (the
    // b64-of-18-byte hash format), if mtime > week old, unlink it.
    // Count the survivors.
    //
    // `count == 0` after the sweep means "no live invitations" → safe
    // to rotate the invitation key. A leaked key from an old invite
    // is now useless: the new key has a different fingerprint.
    let live_count = sweep_expired(&inv_dir, now)?;

    // ─── Load or generate invitation key
    let key_path = paths.invitation_key();

    // No live invitations → drop the old key. The next block then
    // sees ENOENT and generates a fresh one. "Rotate on empty."
    if live_count == 0 {
        // Best-effort. ENOENT (no key yet) is fine; other errors
        // (EACCES?) would surface in the open below anyway.
        let _ = fs::remove_file(&key_path);
    }

    // ENOENT → generate. read_private's Err covers both ENOENT and
    // bad-PEM. Upstream distinguishes (bails on non-ENOENT); we lump
    // them — corrupt-key → regenerate is more useful than bailing.
    let (sk, key_is_new) = if let Ok(sk) = keypair::read_private(&key_path) {
        (sk, false)
    } else {
        let sk = keypair::generate();
        write_invitation_key(&key_path, &sk)?;
        // We set the flag; the binary wrapper attempts the reload.
        (sk, true)
    };

    // ─── The crypto kernel (KAT-tested in tinc-crypto)

    // Cookie: 18 fresh random bytes. Zeroizing — the cookie is the secret.
    let mut cookie = Zeroizing::new([0u8; COOKIE_LEN]);
    OsRng.fill_bytes(&mut *cookie);

    // The pubkey is what fingerprint/key_hash/cookie_hash all derive
    // from. SigningKey carries it.
    let pubkey = sk.public_key();

    // Filename = b64_url(sha512(cookie || b64(pubkey))[..18]).
    // 24 chars, doesn't reveal the cookie.
    let inv_filename = cookie_filename(&cookie, pubkey);
    let inv_path = inv_dir.join(&inv_filename);

    // ─── Write the invitation file
    // O_EXCL, 0600. EXCL: cookie collision is cryptographically
    // impossible (18 bytes from OsRng), so EEXIST means something is
    // very wrong.
    //
    // We build the *whole* file as a string then write_all once.
    // Easier to test (the builder is a separate fn), no partial-write
    // risk, and the file is a few KB at most.
    let body = build_invitation_file(paths, netname, invitee, &myname, &address)?;
    write_invitation_file(&inv_path, &body)?;

    // ─── Build the URL
    // The address already has [:port] formatting from get_my_address.
    let slug = Zeroizing::new(build_slug(pubkey, &cookie));
    let url = Zeroizing::new(format!("{address}/{}", *slug));

    // TODO(chunk-8): execute_script("invitation-created") — lifts to
    // shared script.rs with daemon's execute_script.

    Ok(InviteResult { url, key_is_new })
}

// Helpers

/// Expiry sweep + live count.
///
/// Walks `inv_dir`, for each entry with a 24-char name:
/// - if `mtime + 1 week < now`, unlink it
/// - else, count it as live
///
/// 24 chars is `SLUG_PART_LEN` — the b64-of-18-bytes shape. Any other
/// filename (`.`, `..`, `ed25519_key.priv`) is skipped.
///
/// `now` parameterized so tests don't need to mess with file mtimes.
fn sweep_expired(inv_dir: &Path, now: SystemTime) -> Result<u32, CmdError> {
    let deadline = now.checked_sub(EXPIRY).unwrap_or(SystemTime::UNIX_EPOCH);

    let mut count = 0u32;
    let entries = fs::read_dir(inv_dir).map_err(io_err(inv_dir))?;
    for entry in entries {
        // We propagate per-entry errors immediately — if readdir
        // fails partway, the count is meaningless anyway.
        let entry = entry.map_err(io_err(inv_dir))?;
        let name = entry.file_name();

        // The 24-char filter. `OsStr::len()` is bytes; on Unix that's
        // fine. The b64 alphabet is all ASCII, so 24 bytes = 24 chars.
        if name.len() != SLUG_PART_LEN {
            continue;
        }

        let path = entry.path();
        // stat failure is logged-and-skipped, not fatal — `metadata`
        // failing on a single file shouldn't kill the whole sweep.
        let Ok(meta) = entry.metadata() else {
            continue;
        };
        let Ok(mtime) = meta.modified() else {
            // Platform without mtime support? Treat as live; safer
            // than deleting.
            count += 1;
            continue;
        };

        if mtime < deadline {
            // Best-effort; if it fails the next sweep retries.
            let _ = fs::remove_file(&path);
        } else {
            count += 1;
        }
    }
    Ok(count)
}

/// Write the invitation private key.
///
/// `OpenOptions::mode(0600)` sets the mode atomically at create time
/// (upstream does `fopen("w")` then `chmod` after, with a race window
/// where the file is 0644).
///
/// NOT `O_EXCL` — we just unlinked it (or it didn't exist).
fn write_invitation_key(path: &Path, sk: &SigningKey) -> Result<(), CmdError> {
    use tinc_conf::pem::write_pem;

    let f = super::open_nofollow(path, super::OpenKind::CreateTrunc, 0o600)?;
    let mut w = std::io::BufWriter::new(f);
    // Same PEM type string as the node's own key; the daemon
    // distinguishes them by *path*, not by PEM type.
    write_pem(&mut w, "ED25519 PRIVATE KEY", &sk.to_blob()).map_err(io_err(path))
}

/// Write the invitation file at 0600 with `O_EXCL`.
fn write_invitation_file(path: &Path, body: &str) -> Result<(), CmdError> {
    let mut f = super::open_nofollow(path, super::OpenKind::CreateExcl, 0o600)?;
    f.write_all(body.as_bytes()).map_err(io_err(path))
}

/// Build the invitation file body.
///
/// The file is two chunks separated by `#--...--#`:
/// 1. The invitee's bootstrap config: `Name`, `NetName`, `ConnectTo`,
///    plus copies of `Mode`/`Broadcast` from our tinc.conf.
/// 2. Our own host config (with `Port` substituted if it was `0`).
///
/// `finalize_join` parses the first chunk variable-by-variable through
/// the `VAR_SAFE` filter, then writes subsequent chunks (separated by
/// `Name = X` lines) as host files verbatim. So this format is
/// daemon-locked: chunk 1 = invitee's config, chunk 2+ = host files.
///
/// Separated from `invite()` so tests can check the format without
/// touching the filesystem.
fn build_invitation_file(
    paths: &Paths,
    netname: Option<&str>,
    invitee: &str,
    myname: &str,
    address: &AddressPort,
) -> Result<String, CmdError> {
    let mut out = String::new();

    // ─── Chunk 1: invitee's bootstrap config
    // `Name = X` is the FIRST line; `finalize_join` reads it to know
    // what node it's becoming. Must be first — `get_value` finds the
    // first match.
    out.push_str("Name = ");
    out.push_str(invitee);
    out.push('\n');

    // Only emitted if netname is set. We don't have `check_netname`
    // ported yet; the binary's `-n` parser already does a
    // path-traversal guard, and `finalize_join` re-validates on the
    // receiving side anyway. So: if set, emit it; let join's filter
    // catch bad values.
    //
    // TODO: port `check_netname` to names.rs when more callers need
    // it. ~20 lines: rejects control chars, / \, shell metachars.
    if let Some(n) = netname {
        out.push_str("NetName = ");
        out.push_str(n);
        out.push('\n');
    }

    // Tells the new node who to connect to.
    out.push_str("ConnectTo = ");
    out.push_str(myname);
    out.push('\n');

    // Scan tinc.conf for Mode/Broadcast and copy them. These are the
    // "mesh shape" vars — switch vs router, broadcast yes/no — that
    // the new node needs to match. Everything else is per-node.
    copy_mesh_vars(paths, &mut out)?;

    out.push_str(SEPARATOR);
    out.push('\n');

    // ─── Chunk 2: our host config
    out.push_str("Name = ");
    out.push_str(myname);
    out.push('\n');

    copy_host_replacing_port(&paths.host_file(myname), &address.port, &mut out)?;

    Ok(out)
}

/// Copy `Mode` and `Broadcast` from tinc.conf into the invitation.
///
/// We use `tinc-conf` to parse and re-emit canonically. Whitespace
/// differences in the source (`Mode=switch` vs `Mode = switch`)
/// become canonical in the invitation. Doesn't matter —
/// `finalize_join` re-parses and emits canonically anyway.
fn copy_mesh_vars(paths: &Paths, out: &mut String) -> Result<(), CmdError> {
    let tc = paths.tinc_conf();
    let entries =
        parse_file(&tc).map_err(|e| CmdError::BadInput(format!("{}: {e}", tc.display())))?;
    let mut cfg = Config::new();
    cfg.merge(entries);

    // Just two vars. `lookup` is case-insensitive. Upstream copies
    // every matching line; we copy first only — the daemon's config
    // reader takes first-wins, so duplicates are noise (and an fsck
    // warning anyway).
    for var in &["Mode", "Broadcast"] {
        if let Some(entry) = cfg.lookup(var).next() {
            out.push_str(var);
            out.push_str(" = ");
            out.push_str(entry.get_str());
            out.push('\n');
        }
    }
    Ok(())
}

/// Copies `hosts/myname` line-by-line, but: if a line's variable name
/// is `Port`, replace the whole line with `Port = ACTUAL_PORT`. This
/// handles the `Port = 0` case (ephemeral port) — the invitation needs
/// the *actual* port the daemon bound, not `0`.
///
/// In our case (no daemon connection) we use whatever port was in the
/// `Address` line, or `655` default. The `Port = 0` substitution still
/// happens, just with whatever port `get_my_address` resolved to. If
/// the user has `Port = 0` AND no port on their `Address` line AND no
/// daemon running, they get `Port = 655` here, which is wrong but at
/// least it's a sensible default — and they'll find out when join fails
/// to connect.
///
/// This is the **byte-preserving** copy. Unlike `copy_mesh_vars`, the
/// host file may contain a PEM block, comments, blank lines — things
/// `parse_file` would silently drop. So `read_line` loop, not parse.
/// Same lesson as `disable_old_keys`: byte-level passthrough needs
/// `read_line`, not tinc-conf.
fn copy_host_replacing_port(
    host_file: &Path,
    port: &str,
    out: &mut String,
) -> Result<(), CmdError> {
    // Extract the first whitespace-delimited token (after leading
    // whitespace). Match: token is exactly 4 chars AND those 4 chars
    // are "Port" case-insensitively. "Port" matches, "PORT" matches,
    // "Porting" does NOT (token is 7 chars).
    //
    // Subtlety: token stops at TAB or SPACE but NOT at `=`. So
    // `Port=655` has token "Port=655" (8 chars), doesn't match.
    // `Port=655` passes through unchanged. We replicate; init writes
    // `Port = X` form anyway.
    //
    // `split_inclusive('\n')`: each chunk includes its trailing `\n`
    // (if there was one). Same fidelity as a `read_line` loop.
    let body = fs::read_to_string(host_file).map_err(io_err(host_file))?;

    for chunk in body.split_inclusive('\n') {
        let trimmed = chunk.strip_suffix('\n').unwrap_or(chunk);

        // Leading whitespace skipped, then first token until \t or space.
        let after_lead = trimmed.trim_start_matches([' ', '\t']);
        let token_end = after_lead.find([' ', '\t']).unwrap_or(after_lead.len());
        let token = &after_lead[..token_end];

        if token.len() == 4 && token.eq_ignore_ascii_case("Port") {
            // Replace. Always emits a newline regardless of whether
            // the input chunk had one.
            out.push_str("Port = ");
            out.push_str(port);
            out.push('\n');
        } else {
            // Pass through verbatim, including whatever newline
            // (or lack thereof) the chunk had.
            out.push_str(chunk);
        }
    }
    Ok(())
}

/// Our address for the URL host part. `host[:port]` formatted.
///
/// Upstream's `get_my_hostname` is 190 lines: scan host file → scan
/// tinc.conf → read pidfile → HTTP probe → tty prompt. We do the
/// first two and bail with a clear message.
///
/// The pidfile read is for `Port = 0` resolution: the daemon writes
/// its actual bound port there. Without a daemon connection we can't
/// get that, so `Port = 0` + no port on the `Address` line = error.
/// (`Port` defaults to 655 if absent; `0` is explicit "ephemeral".)
fn get_my_address(paths: &Paths, myname: &str) -> Result<AddressPort, CmdError> {
    // We handle `Address = host port` (port-on-address-line) —
    // `Address = 1.2.3.4 1234` ≡ `Address = 1.2.3.4` + `Port = 1234`.
    //
    // We skip the tinc.conf fallback for Address — it's a host var,
    // not a server var; fsck would warn (`HostVarInServer`). If
    // someone has that setup, they'll get "set Address in your host
    // file" which is the right fix.

    let host_file = paths.host_file(myname);
    let entries = parse_file(&host_file)
        .map_err(|e| CmdError::BadInput(format!("{}: {e}", host_file.display())))?;
    let mut cfg = Config::new();
    cfg.merge(entries);

    // Address: required. C falls through to HTTP probe + tty prompt;
    // we bail. The error message tells the user what to do.
    let Some(addr_entry) = cfg.lookup("Address").next() else {
        return Err(CmdError::BadInput(format!(
            "No Address found in {}.\n  hint: run `tinc -n NET add Address <public-ip-or-hostname>` before creating invitations.",
            host_file.display()
        )));
    };
    let addr_value = addr_entry.get_str();

    // After `Address = X Y`, X is hostname, Y (if present) is port.
    // tinc-conf gives us the raw value after `=`; split once.
    let mut parts = addr_value.split_whitespace();
    let host = parts
        .next()
        .ok_or_else(|| CmdError::BadInput("Address value is empty".into()))?
        .to_owned();
    let addr_line_port = parts.next().map(str::to_owned);

    // Port: from Address line (highest precedence), then `Port =`
    // config entry, then default 655.
    let port = if let Some(p) = addr_line_port {
        p
    } else if let Some(port_entry) = cfg.lookup("Port").next() {
        let p = port_entry.get_str().to_owned();
        // Port=0 means ephemeral; the daemon writes the real port to
        // the pidfile. No daemon → can't resolve → bail.
        if p == "0" {
            return Err(CmdError::BadInput(
                "Port = 0 means dynamic port allocation, but tincd is not running. \
                 Please start tincd or set Port to a fixed value."
                    .into(),
            ));
        }
        p
    } else {
        // Default port: 655. `cmd_join` uses `"655"` if no port in
        // URL; daemon binds 655 by default. All consistent.
        String::from("655")
    };

    Ok(AddressPort { host, port })
}

/// Host + port pair, with the URL formatting that handles IPv6.
///
/// Separate struct (not a tuple) because the formatting rule is
/// non-obvious and lives with the data: IPv6 literals need `[]`
/// brackets in URLs.
#[derive(Debug)]
struct AddressPort {
    host: String,
    /// Kept as a string, not u16: ports can be service names
    /// (`Port = tinc` → `getaddrinfo("tinc")` → 655). String
    /// round-trips.
    port: String,
}

impl std::fmt::Display for AddressPort {
    /// The colon check is a "is this IPv6" heuristic; hostnames
    /// can't contain colons, IPv4 can't, only IPv6 literals do.
    /// `[::1]:655` not `::1:655` (ambiguous).
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.host.contains(':') {
            write!(f, "[{}]:{}", self.host, self.port)
        } else {
            write!(f, "{}:{}", self.host, self.port)
        }
    }
}

// Tests

#[cfg(all(test, unix))]
mod tests {
    use super::*;
    use crate::cmd::init;
    use crate::names::PathsInput;
    use std::os::unix::fs::PermissionsExt;
    use std::path::PathBuf;

    /// Per-test confbase. Test name + thread id for hermeticity.
    fn paths_at(dir: &tempfile::TempDir) -> (PathBuf, Paths) {
        let confbase = dir.path().join("vpn");
        let paths = Paths::for_cli(&PathsInput {
            confbase: Some(confbase.clone()),
            ..Default::default()
        });
        (confbase, paths)
    }

    /// `tinc init NAME` then append `Address = HOST` to `hosts/NAME`.
    /// init doesn't write Address (it's per-installation, not
    /// per-node-identity); invite needs it.
    fn init_with_address(paths: &Paths, name: &str, addr: &str) {
        init::run(paths, name).unwrap();
        let host_file = paths.host_file(name);
        let mut f = fs::OpenOptions::new()
            .append(true)
            .open(&host_file)
            .unwrap();
        writeln!(f, "Address = {addr}").unwrap();
    }

    // copy_host_replacing_port — the C tokenizer port

    /// `copy_host_replacing_port` table. Helper closure does the
    /// tempdir+write+call dance once per row.
    #[test]
    fn copy_host_table() {
        let case = |input: &str, port: &str, expected: &str| {
            let dir = tempfile::tempdir().unwrap();
            let f = dir.path().join("h");
            fs::write(&f, input).unwrap();
            let mut out = String::new();
            copy_host_replacing_port(&f, port, &mut out).unwrap();
            assert_eq!(out, expected, "input: {input:?} port: {port:?}");
        };

        // Port line replaced, everything else byte-preserved.
        case(
            "Address = 1.2.3.4\nPort = 0\nEd25519PublicKey = abc\n",
            "12345",
            "Address = 1.2.3.4\nPort = 12345\nEd25519PublicKey = abc\n",
        );
        // `Port=655` (no space before `=`) does NOT match. The
        // tokenizer stops at whitespace, not `=`, so the token is
        // `Port=655` (8 chars), not `Port` (4 chars).
        case("Port=0\n", "12345", "Port=0\n");
        // No trailing newline on last line: preserved.
        case("Subnet = 10.0.0.0/24", "655", "Subnet = 10.0.0.0/24");
        // Case-insensitive match. Both replaced.
        case("PORT = 0\nport = 1\n", "x", "Port = x\nPort = x\n");
        // PEM block preserved byte-exact. This is why we DON'T use
        // `parse_file` for the host copy — it would silently drop the
        // PEM block (and comments, and blank lines).
        let pem =
            "-----BEGIN ED25519 PUBLIC KEY-----\nbase64here\n-----END ED25519 PUBLIC KEY-----\n";
        case(
            &format!("Port = 1\n{pem}"),
            "655",
            &format!("Port = 655\n{pem}"),
        );
    }

    // get_my_address

    #[test]
    fn address_basic() {
        let dir = tempfile::tempdir().unwrap();
        let (_, paths) = paths_at(&dir);
        init_with_address(&paths, "alice", "myhost.example");
        let a = get_my_address(&paths, "alice").unwrap();
        assert_eq!(a.host, "myhost.example");
        assert_eq!(a.port, "655"); // default
        assert_eq!(a.to_string(), "myhost.example:655");
    }

    #[test]
    fn address_with_port_on_line() {
        let dir = tempfile::tempdir().unwrap();
        let (_, paths) = paths_at(&dir);
        init_with_address(&paths, "alice", "1.2.3.4 9999");
        let a = get_my_address(&paths, "alice").unwrap();
        assert_eq!(a.host, "1.2.3.4");
        assert_eq!(a.port, "9999");
    }

    #[test]
    fn address_ipv6_brackets() {
        let dir = tempfile::tempdir().unwrap();
        let (_, paths) = paths_at(&dir);
        init_with_address(&paths, "alice", "fe80::1");
        let a = get_my_address(&paths, "alice").unwrap();
        // Colon in host → bracketed in URL.
        assert_eq!(a.to_string(), "[fe80::1]:655");
    }

    #[test]
    fn address_port_from_config() {
        let dir = tempfile::tempdir().unwrap();
        let (_, paths) = paths_at(&dir);
        init_with_address(&paths, "alice", "myhost");
        let mut f = fs::OpenOptions::new()
            .append(true)
            .open(paths.host_file("alice"))
            .unwrap();
        writeln!(f, "Port = 1234").unwrap();
        let a = get_my_address(&paths, "alice").unwrap();
        assert_eq!(a.port, "1234");
    }

    #[test]
    fn address_port_zero_bails() {
        let dir = tempfile::tempdir().unwrap();
        let (_, paths) = paths_at(&dir);
        init_with_address(&paths, "alice", "myhost");
        let mut f = fs::OpenOptions::new()
            .append(true)
            .open(paths.host_file("alice"))
            .unwrap();
        writeln!(f, "Port = 0").unwrap();
        let err = get_my_address(&paths, "alice").unwrap_err();
        let CmdError::BadInput(msg) = err else {
            panic!("wrong variant: {err:?}")
        };
        assert!(msg.contains("dynamic port"), "{msg}");
        assert!(msg.contains("tincd"), "{msg}");
    }

    #[test]
    fn address_missing_bails() {
        let dir = tempfile::tempdir().unwrap();
        let (_, paths) = paths_at(&dir);
        init::run(&paths, "alice").unwrap(); // no Address
        let err = get_my_address(&paths, "alice").unwrap_err();
        let CmdError::BadInput(msg) = err else {
            panic!("wrong variant: {err:?}")
        };
        assert!(msg.contains("No Address"), "{msg}");
    }

    // sweep_expired

    /// 24-char filename → counted. Other lengths → ignored. The
    /// `ed25519_key.priv` (16 chars) and `.` `..` filter.
    #[test]
    fn sweep_filters_by_filename_length() {
        let dir = tempfile::tempdir().unwrap();
        let inv = dir.path().join("inv");
        fs::create_dir(&inv).unwrap();

        // 24 chars: counted.
        fs::write(inv.join("a".repeat(24)), "").unwrap();
        fs::write(inv.join("b".repeat(24)), "").unwrap();
        // 16 chars (the key): not counted.
        fs::write(inv.join("ed25519_key.priv"), "").unwrap();
        // 23 chars: not counted.
        fs::write(inv.join("c".repeat(23)), "").unwrap();

        let count = sweep_expired(&inv, SystemTime::now()).unwrap();
        assert_eq!(count, 2);

        // Nothing deleted (all fresh).
        assert_eq!(fs::read_dir(&inv).unwrap().count(), 4);
    }

    /// Expired files deleted, fresh files survive. `now` parameterized
    /// so we don't need to mess with futimes.
    #[test]
    fn sweep_deletes_expired() {
        let dir = tempfile::tempdir().unwrap();
        let inv = dir.path().join("inv");
        fs::create_dir(&inv).unwrap();

        let live = inv.join("a".repeat(24));
        let dead = inv.join("z".repeat(24));
        fs::write(&live, "").unwrap();
        fs::write(&dead, "").unwrap();

        // mtime is "now" for both. To make `dead` expired, advance
        // `now` past it but not past `live`. But they have the same
        // mtime... so we set `dead`'s mtime to the past instead.
        //
        // `filetime` crate? No new deps. Use `nix::sys::stat::utimes`.
        // Actually simpler: just shift `now` for the sweep. Both files
        // have the same mtime so they'd both be live or both dead.
        // To distinguish, we DO need to set one's mtime.
        //
        // Simplest: write `dead`, sleep, write `live`, then `now =
        // dead's mtime + 8 days`. But sleep in tests is bad.
        //
        // Use `nix` directly — it's already a dep.
        let old = SystemTime::UNIX_EPOCH + Duration::from_secs(1_000_000);
        let old_tv = nix::sys::time::TimeVal::new(1_000_000, 0);
        nix::sys::stat::utimes(&dead, &old_tv, &old_tv).unwrap();

        // now = 8 days after `dead`'s mtime. `dead` is expired
        // (deadline = now - 7d = old + 1d > old). `live` has mtime
        // = real-now, well after the deadline.
        let sweep_now = old + Duration::from_secs(8 * 86400);

        let count = sweep_expired(&inv, sweep_now).unwrap();
        assert_eq!(count, 1, "live should be counted, dead should not");
        assert!(live.exists());
        assert!(!dead.exists(), "dead should be deleted");
    }

    // invite() — the contract test

    /// Full invite on a clean init: creates invitations/, key, file,
    /// returns a 48-char-slug URL. **The contract test.**
    ///
    /// What this proves over the unit tests above: the pieces compose.
    /// `invite()` is the seam — every helper is exercised.
    #[test]
    fn invite_full_flow() {
        let dir = tempfile::tempdir().unwrap();
        let (confbase, paths) = paths_at(&dir);
        init_with_address(&paths, "alice", "myhost.example");

        let r = invite(&paths, Some("testnet"), "bob", SystemTime::now()).unwrap();

        // Key was freshly generated (first invite).
        assert!(r.key_is_new);

        // URL shape: host:port/slug, slug is 48 chars.
        let url = r.url.as_str();
        let slash = url.rfind('/').unwrap();
        assert_eq!(&url[..slash], "myhost.example:655");
        let slug = &url[slash + 1..];
        assert_eq!(slug.len(), tinc_crypto::invite::SLUG_LEN);

        // Slug parses. (KAT proves the bytes are right; this proves
        // `invite()` actually called `build_slug`.)
        let (hash, cookie) = tinc_crypto::invite::parse_slug(slug).unwrap();

        // invitations/ exists, mode 0700.
        let inv_dir = confbase.join("invitations");
        let mode = fs::metadata(&inv_dir).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o700);

        // Invitation key exists, mode 0600, loads.
        let key_path = inv_dir.join("ed25519_key.priv");
        assert!(key_path.exists());
        let kmode = fs::metadata(&key_path).unwrap().permissions().mode();
        assert_eq!(kmode & 0o777, 0o600);
        let sk = keypair::read_private(&key_path).unwrap();

        // **The contract**: the URL's key_hash matches the key on
        // disk. This is what `cmd_join` will verify after the daemon
        // greeting — if it fails, "Peer has an invalid key".
        assert_eq!(hash, tinc_crypto::invite::key_hash(sk.public_key()));

        // **The other contract**: the invitation file's name is
        // recoverable from (cookie, key). This is what the daemon
        // does in `receive_invitation_sptps`. If it fails,
        // "non-existing invitation".
        let expected_filename = tinc_crypto::invite::cookie_filename(&cookie, sk.public_key());
        let inv_file = inv_dir.join(&expected_filename);
        assert!(
            inv_file.exists(),
            "filename should be recoverable from cookie+key; \
             expected {expected_filename}, dir has: {:?}",
            fs::read_dir(&inv_dir)
                .unwrap()
                .map(|e| e.unwrap().file_name())
                .collect::<Vec<_>>()
        );

        // Invitation file mode 0600.
        let fmode = fs::metadata(&inv_file).unwrap().permissions().mode();
        assert_eq!(fmode & 0o777, 0o600);

        // File contents: chunk 1 has Name=bob first, NetName,
        // ConnectTo=alice. Chunk 2 has Name=alice + alice's host
        // config (with the pubkey).
        let body = fs::read_to_string(&inv_file).unwrap();
        assert!(
            body.starts_with("Name = bob\n"),
            "Name must be first line: {body}"
        );
        assert!(body.contains("NetName = testnet\n"));
        assert!(body.contains("ConnectTo = alice\n"));
        assert!(body.contains(SEPARATOR));
        // Chunk 2 starts with Name = alice.
        let chunk2 = body.split(SEPARATOR).nth(1).unwrap();
        assert!(chunk2.contains("Name = alice\n"));
        // alice's pubkey is in chunk 2 (init wrote it as a config line).
        assert!(chunk2.contains("Ed25519PublicKey = "));
    }

    /// Second invite reuses the key (not freshly generated). The
    /// "rotate on empty" logic only fires when count == 0.
    #[test]
    fn second_invite_reuses_key() {
        let dir = tempfile::tempdir().unwrap();
        let (_, paths) = paths_at(&dir);
        init_with_address(&paths, "alice", "myhost");

        let r1 = invite(&paths, None, "bob", SystemTime::now()).unwrap();
        assert!(r1.key_is_new);

        let r2 = invite(&paths, None, "carol", SystemTime::now()).unwrap();
        assert!(!r2.key_is_new, "second invite should reuse key");

        // Same key → same key_hash in both URLs.
        let slug1 = r1.url.rsplit('/').next().unwrap();
        let slug2 = r2.url.rsplit('/').next().unwrap();
        assert_eq!(
            slug1[..SLUG_PART_LEN],
            slug2[..SLUG_PART_LEN],
            "key_hash should match (same invitation key)"
        );
        // Different cookies → different cookie halves.
        assert_ne!(slug1[SLUG_PART_LEN..], slug2[SLUG_PART_LEN..]);
    }

    /// invite("alice") when hosts/alice already exists → fail.
    /// You can't invite a node you already know about.
    #[test]
    fn invite_existing_host_fails() {
        let dir = tempfile::tempdir().unwrap();
        let (_, paths) = paths_at(&dir);
        init_with_address(&paths, "alice", "myhost");
        // hosts/alice exists (init created it). Inviting alice fails.
        let err = invite(&paths, None, "alice", SystemTime::now()).unwrap_err();
        let CmdError::BadInput(msg) = err else {
            panic!("wrong variant: {err:?}")
        };
        assert!(msg.contains("already exists"));
    }

    /// invite with no Address → clear error before any files created.
    /// The "fail early" reorder.
    #[test]
    fn invite_no_address_fails_clean() {
        let dir = tempfile::tempdir().unwrap();
        let (confbase, paths) = paths_at(&dir);
        init::run(&paths, "alice").unwrap(); // no Address

        let err = invite(&paths, None, "bob", SystemTime::now()).unwrap_err();
        let CmdError::BadInput(msg) = err else {
            panic!("wrong variant: {err:?}")
        };
        assert!(msg.contains("No Address"));

        // **Nothing created.** Upstream would have made invitations/
        // and possibly written a key by this point. Our reorder
        // means a no-Address failure leaves no trace.
        assert!(
            !confbase.join("invitations").exists(),
            "no-Address failure should not create invitations/"
        );
    }

    /// Invalid invitee name → fail before anything else.
    #[test]
    fn invite_bad_name_fails() {
        let dir = tempfile::tempdir().unwrap();
        let (_, paths) = paths_at(&dir);
        init_with_address(&paths, "alice", "myhost");
        let err = invite(&paths, None, "../etc", SystemTime::now()).unwrap_err();
        assert!(matches!(err, CmdError::BadInput(_)));
    }

    /// `Mode` and `Broadcast` from tinc.conf get copied. Nothing
    /// else does.
    #[test]
    fn mesh_vars_copied() {
        let dir = tempfile::tempdir().unwrap();
        let (confbase, paths) = paths_at(&dir);
        init_with_address(&paths, "alice", "myhost");

        let mut tc = fs::OpenOptions::new()
            .append(true)
            .open(confbase.join("tinc.conf"))
            .unwrap();
        // Mode and Broadcast → copied. Device → not copied.
        writeln!(tc, "Mode = switch").unwrap();
        writeln!(tc, "Broadcast = no").unwrap();
        writeln!(tc, "Device = /dev/net/tun").unwrap();
        drop(tc);

        let r = invite(&paths, None, "bob", SystemTime::now()).unwrap();
        let slug = r.url.rsplit('/').next().unwrap();
        let (_, cookie) = tinc_crypto::invite::parse_slug(slug).unwrap();
        let sk = keypair::read_private(&paths.invitation_key()).unwrap();
        let inv_file = paths
            .invitations_dir()
            .join(tinc_crypto::invite::cookie_filename(
                &cookie,
                sk.public_key(),
            ));
        let body = fs::read_to_string(inv_file).unwrap();

        // Chunk 1 (before separator) has Mode + Broadcast.
        let chunk1 = body.split(SEPARATOR).next().unwrap();
        assert!(chunk1.contains("Mode = switch\n"));
        assert!(chunk1.contains("Broadcast = no\n"));
        // Device is NOT copied. Not in the filter.
        assert!(!chunk1.contains("Device"));
    }
}
